# You Can Scrape a Webpage with One Line of Code

I've read lengthy tutorials where the authors have used libraries like urllib and BeautifulSoup and many, many steps to scrape and parse information about sports statistics from web pages. There's a *much* easier way to do it. Use Pandas.

In [1]:
import pandas as pd

The Pandas library in Python includes a scraper that pulls HTML table data into a dataframe in a single step. Simply insert the URL into the `pandas.read_html()` function and assign the resulting object to a variable so you can work with it. 

The caveat is that this works only for text that has been put into table format in the underlying HTML. You can inspect the HTML or just eyeball it. If it appears to be formatted in rows and columns, it's probably table data.

Wikipedia can be a great place to use the Pandas `read_html` tool. If you're looking for something like sports statistics, you'll generally find at least one table on a page. For this tutorial, I'll scrape the Super Bowl LIV page.

In [37]:
data = pd.read_html("https://en.wikipedia.org/wiki/Super_Bowl_LIV")

Done! 

Well, pretty much done. `data` now contains every table on the Super Bowl LIV page, only some of which might be interesting to us. If we look at the length of `data`, we can see there are 24 tables. We'll need to do some inspecting to see if there's anything we want to use.

In [149]:
len(data)

24

The table at index 6 is an example of how Pandas can do a perfect one-step pull of table data. Here are the game statistics by type and team. If I want, I can export this dataframe to a .csv or assign it to a variable and keep working with it.

In [38]:
data[6]

                           Statistic San Francisco 49ers Kansas City Chiefs
0                        First downs                  21                 26
1                First downs rushing                   8                 12
2                First downs passing                  13                 13
3                First downs penalty                   0                  1
4              Third down efficiency                 3/8               6/14
5             Fourth down efficiency                 0/1                2/3
6                    Total net yards                 351                397
7                  Net yards rushing                 141                129
8                   Rushing attempts                  22                 29
9                     Yards per rush                 6.4                4.4
10                     Yards passing                 210                286
11      Passing–completions/attempts               20/31              26/42
12          Times sacked–total yards                 1–9               4–18
13              Interceptions thrown                   2                  2
14          Punt returns–total yards                 1–0                0–0
15       Kickoff returns–total yards                4–61               3–58
16  Interceptions–total return yards                2–10               2–11
17             Punts–average yardage                2–43               2–40
18                      Fumbles–lost                 1–0                3–0
19                   Penalties–yards                5–45               4–24
20                Time of possession               26:47              33:13
21                         Turnovers                   2                  2

Sometimes (especially on Wikipedia) the table is little bit messier. Let's say I want to pull the scoring summary. That turns out to be the table at index 4.

In [39]:
data[4]

,Scoring summary,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Quarter Time Drive Team Scoring information Sc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Quarter,Time,Drive,Drive,Drive,Team,Scoring information,Score,Score
2,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,SF,KC
3,1,7:57,10,62,5:58,SF,38-yard field goal by Robbie Gould,3,0
4,1,0:31,15,75,7:26,KC,"Patrick Mahomes 1-yard touchdown run, Harrison...",3,7
5,2,9:32,9,43,4:36,KC,31-yard field goal by Butker,3,10
6,2,5:05,7,80,4:27,SF,Kyle Juszczyk 15-yard touchdown reception from...,10,10
7,3,9:29,9,60,5:31,SF,42-yard field goal by Gould,13,10
8,3,2:35,6,55,2:48,SF,"Raheem Mostert 1-yard touchdown run, Gould kic...",20,10
9,4,6:13,10,83,2:40,KC,Travis Kelce 1-yard touchdown reception from M...,20,17
10,4,2:44,7,65,2:26,KC,Damien Williams 5-yard touchdown reception fro...,20,24
11,4,1:12,2,42,0:13,KC,"Williams 38-yard touchdown run, Butker kick good",20,31
12,"""TOP"" = time of possession. For other American...","""TOP"" = time of possession. For other American...","""TOP"" = time of possession. For other American...","""TOP"" = time of possession. For other American...","""TOP"" = time of possession. For other American...","""TOP"" = time of possession. For other American...","""TOP"" = time of possession. For other American...",20,31

This is kind of a mess. We've got some NaN values, the wrong header, and a weird bottom row. This particular HTML table is in a nested structure, and Pandas doesn't interpret that structure for us. We'll need to do a little cleanup. 

First we'll first assign it to `df`, the standard variable for dataframe.

In [46]:
df = data[4]

The first two rows and the last row are part of that nested table structure that we don't need. We can pass a list of row numbers into the `drop` function to get rid of them. The default parameter for `axis` is 0, the row axis, so we don't need to specify it.

In [47]:
df = df.drop([0, 1, 12])
df

,Scoring summary,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,SF,KC
3,1,7:57,10,62,5:58,SF,38-yard field goal by Robbie Gould,3,0
4,1,0:31,15,75,7:26,KC,"Patrick Mahomes 1-yard touchdown run, Harrison...",3,7
5,2,9:32,9,43,4:36,KC,31-yard field goal by Butker,3,10
6,2,5:05,7,80,4:27,SF,Kyle Juszczyk 15-yard touchdown reception from...,10,10
7,3,9:29,9,60,5:31,SF,42-yard field goal by Gould,13,10
8,3,2:35,6,55,2:48,SF,"Raheem Mostert 1-yard touchdown run, Gould kic...",20,10
9,4,6:13,10,83,2:40,KC,Travis Kelce 1-yard touchdown reception from M...,20,17
10,4,2:44,7,65,2:26,KC,Damien Williams 5-yard touchdown reception fro...,20,24
11,4,1:12,2,42,0:13,KC,"Williams 38-yard touchdown run, Butker kick good",20,31

This already looks a lot better. Now we just need to fix the column names. It looks like the first row would be a good candidate. Let's inspect it using `iloc`.

In [43]:
df.iloc[0]

Scoring summary                Quarter
Unnamed: 1                        Time
Unnamed: 2                       Plays
Unnamed: 3                       Yards
Unnamed: 4                         TOP
Unnamed: 5                        Team
Unnamed: 6         Scoring information
Unnamed: 7                          SF
Unnamed: 8                          KC
Name: 2, dtype: object

One thing to know about the `iloc` function is that it works by underlying index position, not by the index number or identifier that we see. If you'll notice, the top row is currently at index 2. Using `iloc` to check what row we're calling confirms that we actually need to grab what's at index 0. 

In one step, we can rename the columns using the names in that top row.

In [44]:
df.iloc[0]

Scoring summary                Quarter
Unnamed: 1                        Time
Unnamed: 2                       Plays
Unnamed: 3                       Yards
Unnamed: 4                         TOP
Unnamed: 5                        Team
Unnamed: 6         Scoring information
Unnamed: 7                          SF
Unnamed: 8                          KC
Name: 2, dtype: object

In [42]:
list(df.iloc[0])

['Quarter',
 'Time',
 'Plays',
 'Yards',
 'TOP',
 'Team',
 'Scoring information',
 'SF',
 'KC']

In [45]:
type(df.iloc[0])

pandas.core.series.Series

In [48]:
df.columns = list(df.iloc[0])

In [49]:
# df.columns = df.iloc[0]
df

,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,SF,KC
2,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,SF,KC
3,1,7:57,10,62,5:58,SF,38-yard field goal by Robbie Gould,3,0
4,1,0:31,15,75,7:26,KC,"Patrick Mahomes 1-yard touchdown run, Harrison...",3,7
5,2,9:32,9,43,4:36,KC,31-yard field goal by Butker,3,10
6,2,5:05,7,80,4:27,SF,Kyle Juszczyk 15-yard touchdown reception from...,10,10
7,3,9:29,9,60,5:31,SF,42-yard field goal by Gould,13,10
8,3,2:35,6,55,2:48,SF,"Raheem Mostert 1-yard touchdown run, Gould kic...",20,10
9,4,6:13,10,83,2:40,KC,Travis Kelce 1-yard touchdown reception from M...,20,17
10,4,2:44,7,65,2:26,KC,Damien Williams 5-yard touchdown reception fro...,20,24
11,4,1:12,2,42,0:13,KC,"Williams 38-yard touchdown run, Butker kick good",20,31

Now we need to drop the first row. The `drop` function, unlike `iloc`, does not go by underlying index. It identifies what you want to drop by the name of the item. Since the first row has the index name of 2, that's what we'll put into the function to drop the row. We could add `axis=0` as a parameter to indicate that we're dropping a row, but since that's the default, I won't bother.

In [50]:
df = df.drop(2)
df

,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,SF,KC
3,1,7:57,10,62,5:58,SF,38-yard field goal by Robbie Gould,3,0
4,1,0:31,15,75,7:26,KC,"Patrick Mahomes 1-yard touchdown run, Harrison...",3,7
5,2,9:32,9,43,4:36,KC,31-yard field goal by Butker,3,10
6,2,5:05,7,80,4:27,SF,Kyle Juszczyk 15-yard touchdown reception from...,10,10
7,3,9:29,9,60,5:31,SF,42-yard field goal by Gould,13,10
8,3,2:35,6,55,2:48,SF,"Raheem Mostert 1-yard touchdown run, Gould kic...",20,10
9,4,6:13,10,83,2:40,KC,Travis Kelce 1-yard touchdown reception from M...,20,17
10,4,2:44,7,65,2:26,KC,Damien Williams 5-yard touchdown reception fro...,20,24
11,4,1:12,2,42,0:13,KC,"Williams 38-yard touchdown run, Butker kick good",20,31

The last thing to clean up is the index number. This isn't strictly necessary, but it is kind of annoying to look at. We'll use the `reset_index` function and add the parameter `drop=True`. If we don't add the drop parameter, the current (annoying) index will become a new column.

In [51]:
df = df.reset_index(drop=True)
df

,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,SF,KC
0,1,7:57,10,62,5:58,SF,38-yard field goal by Robbie Gould,3,0
1,1,0:31,15,75,7:26,KC,"Patrick Mahomes 1-yard touchdown run, Harrison...",3,7
2,2,9:32,9,43,4:36,KC,31-yard field goal by Butker,3,10
3,2,5:05,7,80,4:27,SF,Kyle Juszczyk 15-yard touchdown reception from...,10,10
4,3,9:29,9,60,5:31,SF,42-yard field goal by Gould,13,10
5,3,2:35,6,55,2:48,SF,"Raheem Mostert 1-yard touchdown run, Gould kic...",20,10
6,4,6:13,10,83,2:40,KC,Travis Kelce 1-yard touchdown reception from M...,20,17
7,4,2:44,7,65,2:26,KC,Damien Williams 5-yard touchdown reception fro...,20,24
8,4,1:12,2,42,0:13,KC,"Williams 38-yard touchdown run, Butker kick good",20,31

Beautiful! We could re-name the index column, but it doesn't really bother me. 

If you know you'll be pulling lots of data in the same format, it's a good idea to make the cleanup steps into a function. Here I'll re-create the steps above, but I'll make dropping the last row its own step. By doing this, the variation in the length of scoring summaries from different football games won't matter. The function will always drop the last row.

In [52]:
def score_table(table):
    """
    Returns a clean dataframe of scoring summary.
    """
    table = table.drop(len(table)-1) # Drop last row
    table = table.drop([0, 1]) 
    table.columns = list(table.iloc[0])
    table = table.drop(2) 
    table = table.reset_index(drop=True) 
    return table

Let's try `score_table` with the Wikipedia page for Super Bowl LIII:

In [53]:
data = pd.read_html("https://en.wikipedia.org/wiki/Super_Bowl_LIII")

In [54]:
score_table(data[4])

,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,NE,LAR
0,2,10:29,7,39,3:29,NE,42-yard field goal by Stephen Gostkowski,3,0
1,3,2:11,10,42,4:22,LAR,53-yard field goal by Greg Zuerlein,3,3
2,4,7:00,5,69,2:49,NE,"Sony Michel 2-yard touchdown run, Gostkowski k...",10,3
3,4,1:12,9,72,3:05,NE,41-yard field goal by Gostkowski,13,3

It works! 

You can use this function to clean Super Bowl scoring summaries on Wikipedia, but you may need to double-check which table contains the scoring summary. For Super Bowl LII, it's the table at index 5.

In [55]:
data = pd.read_html("https://en.wikipedia.org/wiki/Super_Bowl_LII")

In [56]:
score_table(data[5])

,Quarter,Time,Plays,Yards,TOP,Team,Scoring information,PHI,NE
0,1,7:55,14,67,7:05,PHI,25-yard field goal by Jake Elliott,3,0
1,1,4:17,9,67,3:38,NE,26-yard field goal by Stephen Gostkowski,3,3
2,1,2:34,3,77,1:43,PHI,Alshon Jeffery 34-yard touchdown reception fro...,9,3
3,2,8:48,6,65,3:05,PHI,"LeGarrette Blount 21-yard touchdown run, 2-poi...",15,3
4,2,7:24,5,48,1:24,NE,45-yard field goal by Gostkowski,15,6
5,2,2:04,7,90,2:57,NE,"James White 26-yard touchdown run, Gostkowski ...",15,12
6,2,0:34,7,70,1:30,PHI,Foles 1-yard touchdown reception from Trey Bur...,22,12
7,3,12:15,8,75,2:45,NE,Rob Gronkowski 5-yard touchdown reception from...,22,19
8,3,7:18,11,85,4:57,PHI,Corey Clement 22-yard touchdown reception from...,29,19
9,3,3:23,7,75,3:55,NE,Chris Hogan 26-yard touchdown reception from B...,29,26
10,4,14:09,8,51,4:14,PHI,42-yard field goal by Elliott,32,26
11,4,9:22,10,75,4:47,NE,Gronkowski 4-yard touchdown reception from Bra...,32,33
12,4,2:21,14,75,7:01,PHI,Zach Ertz 11-yard touchdown reception from Fol...,38,33
13,4,1:05,4,4,1:04,PHI,46-yard field goal by Elliott,41,33

So there you have it. One line of code gets you all the table data on a page. Most of the time you'll see just one table on a page and it will pull cleanly. If you need to clean it up, though, Pandas has you covered.

**One more thing:**

if you're interested in scraping Wikipedia pages, Pandas is an excellent complement to Python's `wikipedia` library. With `wikipedia` you can get page text, links, and references in one easy step. What you can't get is the table data. Using both tools together will allow you to scrape anything you want from a wiki page.